apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: kubernetes-test-app
